name: example
description: A simple command-line application.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  #match: ^0.1.0
  match:
    path: ../

dev_dependencies:
  pedantic: ^1.9.0
  build_runner:
  #match_generator: ^0.1.0
  match_generator:
    path: ../../match_generator
